### PR TITLE
Logo

### PR DESCRIPTION
**Pull request by thomhurst**

### CODE REVIEW

**Comment by viceroypenguin** [comment]
Nice logo!

**Comment by agray** [comment]
Where did you get the green tick icon from?

Surprisingly, Haven't been able to find an exact match

image

**Comment by thomhurst** [comment]
https://www.iconpacks.net/free-icon/green-check-mark-verified-circle-16223.html

**Comment by agray** [comment]
I suggest your logo should be just this:

image

Looks better imo. More like NUnit and XUnit:

NUnit
image

My Logo is 

image

https://github.com/Sauceforge/Saucery

**Pull request merged**
