### PR TITLE
Switched to the more performant System.Threading.Lock on .NET 9.0+

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
### Please check the following before creating a Pull Request

- If this is a new feature or piece of functionality, have you started a discussion and gotten agreement on it?
- If it fixes a bug or problem, is there an issue to track it? If not, create one first and link it please so there's clear visibility.
- Did you write tests to ensure you code works properly?

### CODE REVIEW

**Comment by thomhurst** [comment]
Looks good! Only thing is I'd prefer to keep the dependencies minimal. Any chance we can do a compiler if statement?

If net 8 > object
If net 9 > Lock

**Comment by MarkCiliaVincenti** [comment]
It's a very micro polyfill dependency and will allow you to use the full feature set of System.Threading.Lock not just using the lock keyword.

**Comment by MarkCiliaVincenti** [comment]
In case it's not clear, I am also the author of the library dependency.

**Comment by MarkCiliaVincenti** [comment]
@thomhurst a new version of Backport.System.Threading.Lock has come out that acts as a source generator and basically dropping the DLL as a dependency. If this new development makes you reconsider, I will amend this PR accordingly.

**Comment by thomhurst** [comment]
If it doesn't bring in anything new to the package then sure!

**Comment by MarkCiliaVincenti** [comment]
Applied in #1234

**Pull request closed without merging**
