### PR TITLE
Dispose CancellationTokenRegistration

### PR DESCRIPTION
**Pull request by campersau**
To unregister callback, so it doesn't get called when task completes in time.

### CODE REVIEW

**Comment by thomhurst** [comment]
If cancellationToken.CanBeCanceled evaluates to false then (cancellationTokenRegistration) will stay null. You then wrap a using around it. Won't that throw a null reference exception?

**Comment by campersau** [comment]
No, the compiler always adds a null check:

```c#
IDisposable? disposable = null;        
using (disposable)
{
}
```
gets lowered to:
```c#
IDisposable disposable = null;
IDisposable disposable2 = disposable;
try
{
}
finally
{
    if (disposable2 != null)
    {
        disposable2.Dispose();
    }
}
```


https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAkgCICWAzgA4D2nAQwBGAGwCmAfnTAufQaLHoAvOgB2AVxEiA3EyaM9mAAzpqMnv2HjaBvQSSGiAX1sukToA==

**Comment by thomhurst** [comment]
> No, the compiler always adds a null check:
> 
> ```cs
> IDisposable? disposable = null;        
> using (disposable)
> {
> }
> ```
> 
> gets lowered to:
> 
> ```cs
> IDisposable disposable = null;
> IDisposable disposable2 = disposable;
> try
> {
> }
> finally
> {
>     if (disposable2 != null)
>     {
>         disposable2.Dispose();
>     }
> }
> ```
> 
> https://sharplab.io/#v2:CYLg1APgAgTAjAWAFBQMwAJboMLoN7LpGYZQAs6AsgBQCU+hxTAkgCICWAzgA4D2nAQwBGAGwCmAfnTAufQaLHoAvOgB2AVxEiA3EyaM9mAAzpqMnv2HjaBvQSSGiAX1sukToA==

Oh nice! TIL.

LGTM then

**Review by thomhurst — APPROVED** [review]

**Comment by thomhurst** [comment]
Thanks for the contribution @campersau

**Pull request merged**
