### PR TITLE
remove ArgumentsAttribute constructor that always throws

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by thomhurst** [comment]
Thanks @SimonCropp - looks like there was an analyzer for this, and now a failing test so that might need to go too

**Comment by SimonCropp** [comment]
@thomhurst done

**Comment by SimonCropp** [comment]
well i remove the test. do i remove the analyser as well?

**Comment by thomhurst** [comment]
> well i remove the test. do i remove the analyser as well?

Tbh I wrote that analyser very early on. If it's basically redundant (because the attribute constructor is redundant) then yeah delete it.

I basically want it to throw if no arguments were provided, and it still will do that right?

**Pull request closed without merging**
